# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-05-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofield', '0002_auto_20180121_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'permissions': (('can_view_audiofile', 'can see Audio Files'),), 'verbose_name': 'audio file', 'verbose_name_plural': 'audio files'},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='tag',
            field=models.CharField(blank=True, help_text='tag used to categorize the audio files', max_length=50, null=True, verbose_name='tag'),
        ),
    ]
